title:
  name: Title
  type: string
  default: Event-Participant Manager

email:
  name: Email
  type: string
  default: no-reply@example.com

email_signature:
  name: Email Signature
  type: text
  default:

event:
  name: Event name
  type: string
  default: event

admin:
  name: Admin role name
  type: string
  default: admin

coordinator:
  name: Coordinator role name
  type: string
  default: coordinator

participant:
  name: Participant role name
  type: string
  default: participant

active_wards:
  name: Active Wards (list numbers separated by commas)
  type: string

webmaster:
  name: Webmaster's email address
  type: string
  default: ''