title:
  name: Title
  type: string
  default: Event-Participant Manager

title_short:
  name: Title (short)
  type: string
  default: EPM

email:
  name: Email
  type: string
  default: no-reply@example.com