development:
  adapter: postgresql
  database: epm_development
  host: localhost

test:
  adapter: postgresql
  database: epm_test
  host: localhost

production:
  adapter: postgresql
  database: epm_production
  host: localhost