development:
  adapter: postgresql
  database: nfftt_development
  host: localhost

test:
  adapter: postgresql
  database: nfftt_test
  host: localhost

production:
  adapter: postgresql
  # adapter: mysql2
  database: nfftt_production
  host: localhost